### ISSUE TITLE
Access to Group Libraries

### ISSUE THREAD

**Issue by MunGell** [MunGell/ZotServer#2]
See https://github.com/vanakat/zotero-link/issues/3

**Comment by jebins** [comment]
Hi,

It would be a very useful feature !

**Comment by e-kotov** [comment]
Vote up!

**Comment by MunGell** [comment]
Hi there, I've just pushed functionality of selecting library to my Zotero Obsidian plugin.
This will only work starting Zotero 7 beta build 88, since it relies on Local API support.

I will not be implementing this functionality for Zotero 6 (through ZotServer).

Hope this works for you!
