### ISSUE TITLE
Fully automatic setup of ZotServer in a headless Linux server

### ISSUE THREAD

**Issue by contrun** [MunGell/ZotServer#4]
Currently it seems that we need to manually install the zotero plugin and then start ZotServer from the command line. All this seems to require GUI interface. I'd like to have ZotServer running in a headless Linux server. Can we provide a script to automatically setup ZotServer? This may be helpful for end users and writing integration tests. Zotero better bibtex does have integration tests by automatically setup zotero in a headless environment https://github.com/retorquere/zotero-better-bibtex/tree/master/test . But it is too complex, we may strip better bibtex's code to suit our needs.

Here is my research for ZotServer to run in a headless Linux server. Please correct me if there is anything that is unnecessarily complex.

1) Automatically install the plugins first. https://github.com/retorquere/zotero-better-bibtex/blob/fac743dd3604224b06af8e64735cdb960b11a010/test/features/steps/zotero.py#L51 installed the zotero better bibtex with selenium https://www.selenium.dev/selenium/docs/api/py/_modules/selenium/webdriver/firefox/firefox_profile.html#FirefoxProfile.add_extension .
2) Setup ZotServer plugins. I don't know it is necessary for ZotServer. https://github.com/retorquere/zotero-better-bibtex/blob/fac743dd3604224b06af8e64735cdb960b11a010/test/features/steps/zotero.py#L585-L596 zotero better bibtex also uses selenium to do that. https://www.selenium.dev/selenium/docs/api/py/_modules/selenium/webdriver/firefox/firefox_profile.html#FirefoxProfile.update_preferences

**Comment by MunGell** [comment]
Hi @contrun 

To be honest with you I am not 100% following on the problem that needs to be solved.
But in case my reading is correct, I was looking to implement a development workflow using Docker containers similar to how it is done in https://github.com/Dominic-DallOsto/zotero-api-endpoint

Would Docker solution be helpful for what you are trying to solve?

**Comment by MunGell** [comment]
Closing this as ZotServer will not be supported starting Zotero 7

See https://github.com/MunGell/ZotServer/issues/5#issuecomment-2169426991
